---
- hosts: clientes
  user: root
  
  tasks:
          - name: installing Apache2, mysql, etc
            apt:
                    name: "{{ paquete }}"
                    update_cache: yes
            vars:
                    paquete:
                            - apache2
                            - mysql-server
                            - php
                            - unzip
                            - php-mysql
                            - python3
                            - python2.7
                            - python-mysqldb
                            - php-curl
                            - php-gd
                            - php-curl
                            - php-mbstring
                            - php-xml
                            - php-xmlrpc
                            
          - name: creating mysql db 
            mysql_db:
                    name: wordpress
                    state: present
                  

          - name: creating user in mysql db
            mysql_user:
                    name: usuario
                    password: usuario
                    priv: '*.*:ALL'
                    state: present

          - name: downloading wordpress
            get_url:
                    url: https://wordpress.org/latest.tar.gz
                    dest: /var/www/wordpress.tar.gz
                    validate_certs: no
            notify:
                    - unzip wordpress
                    - privilages
      



                    #- name: Eliminando wordpress.tar.gz...
                    #file:
                    #path: /var/www/wordpress.tar.gz
                    #state: absent



                      # - name: Dando privilegios a la carpeta wordpress
                      # file:
                      #path: /var/www/wordpress/
                      # state: directory
                      #owner: www-data
                      #group: www-data
                      #mode: 0777
          

          - name: Activar rewrite
            apache2_module:
                    name: rewrite
                    state: present
            notify:
                    - restart apache2


          - name: Enviando fichero de configuración del Virtual Host
            copy:
                    src: /home/usuario/010-wordpress.conf
                    dest: /etc/apache2/sites-available/010-wordpress.conf

          - name: Desactivar 000-default.conf
            file:
                    path: /etc/apache2/sites-enabled/000-default.conf
                    state: absent
            notify:
                    - restart apache2

                    
          - name: Activar 010-wordpress.conf
            file:
                    src: /etc/apache2/sites-available/010-wordpress.conf
                    dest: /etc/apache2/sites-enabled/010-wordpress.conf
                    state: link
            notify:
                    - restart apache2


  handlers: 
          - name: restart apache2
            systemd:
                    name: apache2
                    state: restarted

          - name: unzip wordpress
            unarchive:
                    src: /var/www/wordpress.tar.gz
                    dest: /var/www/
                    copy: no

          - name: downloading wordpress
            get_url:
                    url: https://wordpress.org/latest.tar.gz
                    dest: /var/www/wordpress.tar.gz
                    validate_certs: no

          - name: privilages
            file:
                    path: /var/www/wordpress/
                    state: directory
                    owner: www-data
                    group: www-data
                    mode: 0777




                   

